// This file is auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types-generated.ts
// For now, using a minimal type definition.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      topics: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          follower_count: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['topics']['Row'], 'id' | 'created_at' | 'follower_count'>;
        Update: Partial<Database['public']['Tables']['topics']['Insert']>;
      };
      user_topics: {
        Row: {
          id: string;
          user_id: string;
          topic_id: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['user_topics']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['user_topics']['Insert']>;
      };
      tags: {
        Row: {
          id: string;
          name: string;
          slug: string;
          usage_count: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tags']['Row'], 'id' | 'created_at' | 'usage_count'>;
        Update: Partial<Database['public']['Tables']['tags']['Insert']>;
      };
      posts: {
        Row: {
          id: string;
          author_id: string | null;
          source: 'user' | 'system';
          title: string;
          summary: string;
          content: string;
          cover_image: string | null;
          view_count: number;
          like_count: number;
          comment_count: number;
          bookmark_count: number;
          created_at: string;
          updated_at: string;
          published_at: string;
        };
        Insert: Omit<Database['public']['Tables']['posts']['Row'], 'id' | 'created_at' | 'updated_at' | 'view_count' | 'like_count' | 'comment_count' | 'bookmark_count' | 'published_at'>;
        Update: Partial<Database['public']['Tables']['posts']['Insert']>;
      };
      post_topics: {
        Row: {
          id: string;
          post_id: string;
          topic_id: string;
        };
        Insert: Omit<Database['public']['Tables']['post_topics']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['post_topics']['Insert']>;
      };
      post_tags: {
        Row: {
          id: string;
          post_id: string;
          tag_id: string;
        };
        Insert: Omit<Database['public']['Tables']['post_tags']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['post_tags']['Insert']>;
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          author_id: string | null;
          parent_id: string | null;
          content: string;
          like_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['comments']['Row'], 'id' | 'created_at' | 'updated_at' | 'like_count'>;
        Update: Partial<Database['public']['Tables']['comments']['Insert']>;
      };
      likes: {
        Row: {
          id: string;
          user_id: string;
          post_id: string | null;
          comment_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['likes']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['likes']['Insert']>;
      };
      bookmarks: {
        Row: {
          id: string;
          user_id: string;
          post_id: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['bookmarks']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['bookmarks']['Insert']>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'comment' | 'reply' | 'like_post' | 'like_comment' | 'follow_topic' | 'system';
          title: string;
          body: string | null;
          post_id: string | null;
          comment_id: string | null;
          actor_id: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at' | 'is_read'>;
        Update: { is_read?: boolean };
      };
    };
  };
}
